# Generated by Django 5.2.6 on 2026-06-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('New', 'New Lead'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Won', 'Won')], default='New', max_length=50)),
                ('source', models.CharField(choices=[('Meta Ads', 'Meta Ads'), ('Google Ads', 'Google Ads'), ('Website', 'Website'), ('WhatsApp', 'WhatsApp'), ('Referral', 'Referral')], default='Website', max_length=50)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineGrowth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_label', models.CharField(max_length=50)),
                ('leads_count', models.IntegerField(default=0)),
            ],
        ),
    ]
